# Generated by Django 4.0.1 on 2022-01-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.IntegerField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('arrival_timestamp', models.DateTimeField()),
                ('num_passengers', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('sharer_num', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=20, null=True)),
                ('status', models.IntegerField()),
                ('special_req', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('plate_num', models.CharField(max_length=20)),
                ('max_passenger', models.IntegerField()),
                ('special_info', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('curr_role', models.CharField(max_length=10, null=True)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myride.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('sharer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myride.ride')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myride.user'),
        ),
    ]
