# Generated by Django 4.0.1 on 2022-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'not confirmed'), (2, 'confirmed'), (3, 'completed')]),
        ),
    ]
