# Generated by Django 4.0.1 on 2022-01-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myride', '0004_alter_ride_arrival_timestamp_alter_ride_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='driver_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='curr_role',
            field=models.SmallIntegerField(choices=[(1, 'Ride Driver'), (2, 'Ride Owner'), (3, 'Ride Sharer')], null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_passenger',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='special_info',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
