# Generated by Django 4.0.1 on 2022-01-30 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myride', '0005_alter_ride_driver_id_alter_user_curr_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='arrival_timestamp',
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Arrival Date, format: YYYY-MM-DD or MM/DD/YY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Arrival Time, format: HH:MM:SS or HH:MM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharer_num',
            field=models.IntegerField(null=True),
        ),
    ]
