# Generated by Django 4.0.1 on 2022-01-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myride', '0007_user_email_alter_vehicle_special_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='sharer_num',
            field=models.IntegerField(default=1, verbose_name='Number of Sharers'),
            preserve_default=False,
        ),
    ]
